[Feature] projects 관련 API 생성
LemonScone/pixel-art pull request #17
Opened 2023-05-27 02:40 UTC by the1020

## Description

​projects 관련 API 작업 추가합니다.

- [x] /projects/:id (GET): 개별 project를 조회합니다.
- [x] /projects/:id (POST): 신규 project를 생성합니다.
- [x] /projects/:id (PATCH): project를 수정합니다.
- [x] /projects/:id (DELETE): project를 삭제합니다.
- [x] /projects/:id/status (PATCH): 게시 여부를 수정합니다.

---
### 어제 회의 후 변경 사항입니다.
- `HttpException`으로 예외 처리하였습니다.
- INSERT 후 신규 생성된 데이터를 반환합니다.
- 조회를 제외한 모든 서비스는 파라미터로 받은 id를 이용해 해당 프로젝트가 존재하는지 확인 후 쿼리 execute하도록 하였습니다.

## Related Issues

​
resolve #12
​

## Checklist

​
Before you create this PR confirms that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.
​

- [x] Issue TODO finished
- [x] No Conflicts with the base branch

2023-05-27 09:30 UTC, padosum commented on backend/src/projects/projects.service.ts
> +      const queryResult = await connectionPool.query(
INSERT 문 실행 후 `insertId`를 얻을 수 있는 것으로 알고 있습니다. 
더 간편한 경우 수정하면 좋을 것 같습니다.

https://github.com/sidorares/node-mysql2#api-and-configuration
```ts
connection.query('INSERT INTO posts SET ?', {title: 'test'}, function (error, results, fields) {
  if (error) throw error;
  console.log(results.insertId);
});
```

2023-05-27 09:35 UTC, padosum commented on backend/src/projects/projects.service.ts
> +  async deleteProject(id: number): Promise<void> {
`FRAME` 테이블이 `PROJECT` 테이블의 `id`를 외래키로 가지고 있어서 관련 `FRAME` 테이블이 있는 경우 먼저 삭제 후 `PROJECT` 테이블을 삭제해야 합니다. 

[Transaction](https://github.com/mysqljs/mysql#transactions)을 사용하면 좋을 것 같은데 확인부탁드립니다

2023-05-27 09:42 UTC, padosum commented on backend/src/projects/projects.controller.ts
> +  @Get(':id')
어제 회의에서 나온 다음 API 추가가 필요합니다.
`GET /projects`: 로그인된 사용자의 모든 프로젝트 조회한다.

2023-05-27 09:48 UTC, padosum commented on backend/src/projects/projects.controller.ts
> +  }
`/projects/:id` 로 각 `project` 데이터를 가져오기로 했는데 

실제 개발을 할 때 `Frame` table 데이터를 함께 가져오는 것이 좋을까요?
`/projects/:id`를 요청하는 경우가 하나의 프로젝트를 보여주는 화면일 텐데 화면 상단에 Frame 테이블 내용도 조회될 듯 합니다. 
어떻게 생각하시나요??

2023-05-27 09:50 UTC, padosum requested changes
comment 확인 부탁드립니다. 👍

2023-05-29 13:27 UTC, the1020 commented on backend/src/projects/projects.controller.ts
> +  }
`Frame` table 데이터를 함께 가져오는 것으로 결정했습니다.💎

2023-05-29 13:29 UTC, the1020 commented on backend/src/projects/projects.service.ts
> +      const queryResult = await connectionPool.query(
async/await의 results에서 `insertId`를 얻어오겠습니다.

2023-05-29 13:30 UTC, the1020 commented on backend/src/projects/projects.service.ts
> +  async deleteProject(id: number): Promise<void> {
Transaction을 사용하여 `Frame`과 `Project` 테이블 DELETE 처리하도록 하겠습니다.

2023-05-30 07:38 UTC, padosum commented on backend/src/projects/projects.service.ts
> +      await connectionPool.query(query_frame, values_frame);
꿀팁이네요 👍

2023-05-30 07:57 UTC, padosum approved these changes
👍 👍 👍 👍

2023-05-30 07:57 UTC, merged