[Feature] 그림판 UI 작업
LemonScone/pixel-art pull request #33
Opened 2023-06-09 03:52 UTC by padosum

## Description

### 컴포넌트
`PixelContainer`
```ts
type PixelContainerProps = {
  columns: number;
  rows: number;
  grid: string[];
  toolOptions: ToolOption;
  selectedTool: Tool;
  onUpdateGrid: (newGrid: string[]) => void;
};
```
- `columns` x `rows` 만큼 `Pixel` 컴포넌트가 렌더링됩니다.
- `grid`에 색상코드 문자열이 존재할 때 같은 인덱스에 해당하는 pixel에 색상이 채워집니다. 

`Pixel`
```ts
type PixelProps = {
  id: number;
  color: string;
  columns: number;
  toolActive: boolean;
  onPointerDown: (id: number) => void;
  onToolActive: (down: boolean) => void;
};
```
- `onPointerDown`: 해당 pixel의 `id`가 전달되어 `PixelContainer`의 `grid`가 업데이트됩니다.
- `toolActive`: 선택된 툴이 드래그 중인지 확인하는 prop
  - `onPointerDown`에 `true`, `onPointerUp`에 `false`로 처리됨

## Related Issues
​
resolve #31
​

## Checklist

Before you create this PR confirms that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.
​
- [x] Issue TODO finished
- [x] No Conflicts with the base branch

2023-06-12 12:29 UTC, the1020 requested changes

2023-06-12 12:41 UTC, the1020 approved these changes

2023-06-12 12:41 UTC, merged

2023-06-13 04:27 UTC, padosum commented on frontend/src/components/Pixel.tsx
> +      className={`pixel w-[calc(100%/${columns})] h-100 border-r border-b border-neutral-500 hover:bg-zinc-500 transition-all bg-neutral-600`}
추후 작업

2023-06-13 04:28 UTC, padosum commented on frontend/src/utils/grid.ts
> +export const getTargetIndexes = (
추후 작업