[Enhance] Pixel 컴포넌트 리렌더링 개선
LemonScone/pixel-art pull request #75
Opened 2023-06-27 15:48 UTC by the1020

## Description
`Pixel`과 `PixelContainer`의 리렌더링이 자주 발생하고 있습니다. 특히나 `Pixel` 컴포넌트의 불필요한 리렌더링을 제거하였습니다.

- [x] `Pixel` onPointer 이벤트를 상위 컴포넌트인 `PixelContainer`의 onPointer 이벤트에서 처리하도록 하여 리렌더링을 줄였습니다.
- [x] 위 내용처럼 `Pixel`의 onPointer 이벤트는 제거되었으므로 해당 테스트 코드를 제거하였습니다.
- [x] 포인터가 이동할 때(`onPointerMove`), `Pixel` 영역이 변경됐을 때만 `dispatch`를 호출하고 `hoverColor`를 설정/해제하도록 하였습니다.
- [x] 또한 reducer에서 현재 상태값인 origin grid와 dispatch 호출으로 새로 계산된 new grid를 비교하는 메서드를 추가하였습니다. 이 메서드를 통해 배열을 비교하고 배열이 다를 경우에만 상태값을 갱신하도록 하였습니다.
- [x] grid sample의 각 요소를 rgba에서 rgb로 변경하였습니다. 
​

## Related Issues

​
resolve #57 
​

## Checklist

​
Before you create this PR confirms that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.
​

- [x] Issue TODO finished
- [x] No Conflicts with the base branch

2023-06-27 23:27 UTC, padosum commented on frontend/src/reducers/gridReducer.ts
> +
`JSON.stringify`를 사용하면 조금 빠르려나요 ? 
그리고 함수를 `utils` 디렉토리로 이동시키면 좋겠습니다.

2023-06-27 23:29 UTC, padosum requested changes
작업해주신 덕분에 간과하고 있었던 리렌더링 문제가 줄어들어 좋았습니다!

2023-06-28 04:14 UTC, the1020 commented on frontend/src/reducers/gridReducer.ts
> +
![image](https://github.com/LemonScone/pixel-art/assets/11607444/10a7f1fe-35a2-44b5-b19b-5dd00805a1bf)

`JSON.stringify`도 문자열로 변환하기 위해서 모든 배열의 요소를 순회해야 합니다. 하지만 for문의 경우 변경된 픽셀을 찾으면 순회를 중단하고 바로 `return false;`를 반환합니다.
따라서 `JSON.stringify`를 사용하는 것보다 for문으로 순회하는 것이 더 효율적이라고 판단됩니다.

2023-06-28 04:35 UTC, padosum commented on frontend/src/reducers/gridReducer.ts
> +
오 말씀하신대로 생각하니 그게 더 효율적인 것 같습니다. 👍

2023-06-28 04:36 UTC, merged